server:
  port: 9050
  servlet.context-path: /account

spring:
  datasource:
    url: 
    username: 
    password: 
    driver-class-name: org.postgresql.Driver

stripe:
  api:
    secret: 
  webhook:
    secret: 
