spring:
  config:
    activate:
      on-profile: k8s
  kafka:
    bootstrap-servers: kafka.lovable-core.svc.cluster.local:9092
  cloud:
    discovery:
      enabled: false

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

jwt.secretKey: ${JWT_SECRET}

app:
  frontend:
    url: ${FRONTEND_URL}
  preview:
    domain: ${PREVIEW_DOMAIN}
    namespace: ${PREVIEW_NAMESPACE}
    proxy-port: ${PROXY_PORT}

ACCOUNT_SERVICE_URI: http://account-service
WORKSPACE_SERVICE_URI: http://workspace-service
INTELLIGENCE_SERVICE_URI: http://intelligence-service