server:
  port: 9030
  servlet.context-path: /intelligence
logging:
  level:
    org.springframework.security: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:9010/IntelligenceDB
    username: lovable
    password: test123
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org.springframework.ai.chat.client: DEBUG
